## Sound classification techniques_functions from scratch

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A function that implements a linear model function for binary logistic regression

In [3]:
def linear_model_function(data_matrix, weights):
    P=data_matrix
    W=weights
    return P@W

In [7]:
test_data_matrix = np.array([[1, -0.15771414, -0.75293918, -0.0130713],\
                             [1, -0.3521762, 0.19650084, 1.94050566],\
                             [1, 1.30917135,  1.69791787, -0.91502836]])
test_weights = np.array([[0.46390948], [-1.15729779], [0.23372497],
                         [-1.5223521]])

linear_model_function(test_data_matrix, test_weights)

array([[ 0.49035014],
       [-2.0367235 ],
       [ 0.73864952]])

Function that takes an argument named inputs and returns the output of the sigmoid function

In [4]:
def binary_logistic_activation_function(inputs):
    di=1+np.exp(-inputs)
    return 1/di

In [8]:
test_row_inputs = np.array([0, 1, -3, np.log(2), 0.4223615])
binary_logistic_activation_function(test_row_inputs)

array([0.5       , 0.73105858, 0.04742587, 0.66666667, 0.6040482 ])

In [9]:
test_column_inputs = np.array([[-2], [0.5], [np.log(1 / 3)], [0.26478703]])
binary_logistic_activation_function(test_column_inputs)

array([[0.11920292],
       [0.62245933],
       [0.25      ],
       [0.56581268]])

Function takes the argument logistic_values as inputs and returns a vector of class labels with binary values in  {0,1} as its output

In [10]:
def binary_logistic_prediction_function(logistic_values):
    logistic_values[logistic_values < 0.5] = 0
    logistic_values[logistic_values > 0.5] = 1
    return logistic_values

In [11]:
test_logistic_values = np.array([[0.30493025], [0.80419595], [0.56509748], [0.23903961],\
                                 [0.9773376],  [0.28956517], [0.83508464], [0.57761601],\
                                 [0.41169655], [0.97455507], [0.1095421],  [0.21852319]])

binary_logistic_prediction_function(test_logistic_values)

array([[0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.]])

Function that takes two inputs true_labels and recovered_labels and returns the percentage of correctly classified labels divided by  100.

In [6]:
def classification_accuracy(true_labels, recovered_labels):
    equal_labels = recovered_labels == true_labels
    return np.mean(equal_labels)

In [12]:
test_true_labels = np.array([[0], [1], [1], [0], [1], [1], [0], [0], [1], [0]])
test_recovered_labels = np.array([[1], [1], [0], [0], [0], [1], [1], [0], [1],
                                  [1]])

classification_accuracy(test_true_labels, test_recovered_labels)

0.5

Write two functions that implement the cost function for binary logistic regression as well as its gradient

In [13]:
def binary_logistic_regression_cost_function(data_matrix, data_labels,
                                             weights):
    B_out = linear_model_function(data_matrix, weights)
    return np.mean(np.log(1 + np.exp(B_out)) - data_labels * B_out)

In [14]:
def binary_logistic_regression_gradient(data_matrix, data_labels, weights):
    B_out = linear_model_function(data_matrix, weights)
    P=data_matrix
    s=len(data_matrix)
    return P.T @ (binary_logistic_activation_function(B_out) - data_labels) / s

In [15]:
test_data_matrix = np.array([[1, -0.12793802, -0.19751682, 0.15226261], [1, -0.2000033, 0.52618148, 0.8782188],\
                             [1, -0.8613664, 0.30565866, -0.49296481], [1, -0.84047233, 0.9252299, 0.99071071],\
                             [1, -0.1042736, 0.52956168, -0.47798761], [1, 0.11284415, -0.94223132, 0.65812316],\
                             [1, -0.24878785, 0.85320211, -0.20377839], [1, 0.86694977, -0.55784702, 0.39560232],\
                             [1, 0.63581885, -0.11724269, -0.0979702], [1, 0.92166492, 0.76064856, 0.20755241]])
test_data_labels = np.array([[0], [1], [1], [1], [0], [1], [0], [0], [1], [0]])
test_weights = np.array([[-0.10541393], [0.57801403], [0.67163957],
                         [-0.34652194]])

binary_logistic_regression_cost_function(data_matrix=test_data_matrix,
                                             data_labels=test_data_labels,
                                             weights=test_weights)

0.846796279379529

In [17]:
test_data_matrix = np.array([[1, -0.12793802, -0.19751682, 0.15226261], [1, -0.2000033, 0.52618148, 0.8782188],\
                             [1, -0.8613664, 0.30565866, -0.49296481], [1, -0.84047233, 0.9252299, 0.99071071],\
                             [1, -0.1042736, 0.52956168, -0.47798761], [1, 0.11284415, -0.94223132, 0.65812316],\
                             [1, -0.24878785, 0.85320211, -0.20377839], [1, 0.86694977, -0.55784702, 0.39560232],\
                             [1, 0.63581885, -0.11724269, -0.0979702], [1, 0.92166492, 0.76064856, 0.20755241]])
test_data_labels = np.array([[0], [1], [1], [1], [0], [1], [0], [0], [1], [0]])
test_weights = np.array([[-0.10541393], [0.57801403], [0.67163957],
                         [-0.34652194]])

binary_logistic_regression_gradient(data_matrix=test_data_matrix,
                                        data_labels=test_data_labels,
                                        weights=test_weights)

array([[-0.006401  ],
       [ 0.15045298],
       [ 0.07449562],
       [-0.12069674]])

 Implementation of a gradient descent method

In [18]:
def gradient_descent(objective,
                     gradient,
                     initial_weights,
                     step_size=1,
                     no_of_iterations=100,
                     print_output=10):
    obj = []
    weights = np.copy(initial_weights)
    N=no_of_iterations
    obj.append(objective(weights))
    
    for i in range(N):
        weights -= step_size * gradient(weights)
        obj.append(objective(weights))
        
        if (i + 1) % print_output == 0:
            print("Iteration {k}/{m}, objective = {o}.".format(k=i+1, m=N, o=obj[i]))
    print("Iteration completed after {k}/{m}, objective = {o}.".format(k=i+ 1, m=N, o=obj[i]))
    
    return weights, obj

gradient_descent_v2 takes an additional argument tolerance that controls the norm of the gradient.

In [20]:
def gradient_descent_v2(objective, gradient, initial_weights, \
                        step_size=1, no_of_iterations=100, print_output=10, tolerance=1e-6):
    obj = []
    L=objective
    weights = np.copy(initial_weights)
    N=no_of_iterations
    obj.append(L(weights))
    
    for i in range(N):
        dL=gradient(weights)
        if np.linalg.norm(dL,2) <= tolerance:
            break
        weights -= step_size * dL
        obj.append(L(weights))
        
        if (i + 1) % print_output == 0:
            print("Iteration {k}/{m}, objective = {o}.".format(k=i+1, m=N, o=obj[i]))
        
        
    print("Iteration completed after {k}/{m}, objective = {o}.".format(k=i+1, m=N, o=obj[i]))
    
    return weights, obj

In [22]:
test_matrix_m = np.array([[3, 1], [2, 4]])
test_vector_v = np.array([5, 6])
test_objective = lambda x: x.T @ (test_matrix_m @ x) + x @ test_vector_v
test_gradient = lambda x: (test_matrix_m + test_matrix_m.T) @ x + test_vector_v
test_initial_weights = np.array([0.0, 0.0])
test_step_size = 0.9 / (np.linalg.norm(test_matrix_m + test_matrix_m.T))
test_no_of_iterations = 100
test_print_output = 10

gradient_descent(test_objective, test_gradient, \
                                           test_initial_weights,test_step_size, \
                                           test_no_of_iterations, test_print_output)[0]

Iteration 10/100, objective = -3.0256011293288547.
Iteration 20/100, objective = -3.0256410067129824.
Iteration 30/100, objective = -3.025641025632046.
Iteration 40/100, objective = -3.0256410256410207.
Iteration 50/100, objective = -3.025641025641026.
Iteration 60/100, objective = -3.0256410256410255.
Iteration 70/100, objective = -3.0256410256410264.
Iteration 80/100, objective = -3.0256410256410255.
Iteration 90/100, objective = -3.0256410256410255.
Iteration 100/100, objective = -3.0256410256410255.
Iteration completed after 100/100, objective = -3.0256410256410255.


array([-0.56410256, -0.53846154])

In [23]:
test_matrix_m = np.array([[3, 1], [2, 4]])
test_vector_v = np.array([5, 6])
test_objective = lambda x: x.T @ (test_matrix_m @ x) + x @ test_vector_v
test_gradient = lambda x: (test_matrix_m + test_matrix_m.T) @ x + test_vector_v
test_initial_weights = np.array([0.0, 0.0])
test_step_size = 0.9 / (np.linalg.norm(test_matrix_m + test_matrix_m.T))
test_no_of_iterations = 100
test_print_output = 10

len(gradient_descent_v2(test_objective, test_gradient, \
                                           test_initial_weights,test_step_size, \
                                           test_no_of_iterations, test_print_output)[1])-1



Iteration 10/100, objective = -3.0256011293288547.
Iteration 20/100, objective = -3.0256410067129824.
Iteration 30/100, objective = -3.025641025632046.
Iteration completed after 36/100, objective = -3.025641025640935.


35

Implementation of the functions on the Spotify music dataset.

To load and store training and testing dataset into corresponding NumPy arrays: spotify_training_data_input, spotify_training_data_labels, spotify_testing_data_input.

In [25]:
spotify_training_data = np.genfromtxt('spotify_training.csv',
                                      skip_header=True,
                                      dtype=None,
                                      delimiter=',')
spotify_testing_data_input = np.genfromtxt('spotify_testing.csv',
                                           skip_header=True,
                                           dtype=None,
                                           delimiter=',')
spotify_training_data_input = spotify_training_data[:, :-1]
spotify_training_data_labels = spotify_training_data[:, -1].reshape(-1, 1)

A function to standardise the columns of a two-dimensional NumPy array data_matrix

In [26]:
def standardise(data_matrix):
    P=data_matrix
    row_means = np.mean(data_matrix, axis=0)
    std_matrix = P - row_means
    row_stds = np.std(std_matrix, axis=0)
    return (std_matrix / row_stds), row_means, row_stds

In [35]:
test_data_matrix = np.array([[1, 2], [3, 4], [5, 6]])
test_standardised_matrix,test_row_of_means,test_row_of_stds = standardise(test_data_matrix)

The function that de-standardises the columns of a two-dimensional NumPy array data_matrix

In [36]:
def de_standardise(standardised_matrix, row_of_means, row_of_stds):
    matrix = np.copy(standardised_matrix * row_of_stds)
    return matrix + row_of_means

In [38]:
de_standardise(test_standardised_matrix, test_row_of_means,
                   test_row_of_stds)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

Apply data standardisation as per above to the Spotify data, both training and testing

In [39]:
spotify_training_data_input, spotify_row_of_avgs, spotify_row_of_stds = standardise(
    spotify_training_data_input)
spotify_testing_data_input = (spotify_testing_data_input -
                              spotify_row_of_avgs) / spotify_row_of_stds

 Implement function linear_regression_data that computes (and outputs) the linear regression data_matrix for a given data_inputs matrix.

In [40]:
def linear_regression_data(data_inputs):
    col=np.ones((len(data_inputs), 1))
    mat=np.c_[col,data_inputs]
    return mat

In [41]:
test_data_inputs = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
linear_regression_data(test_data_inputs)

array([[1., 1., 2.],
       [1., 2., 3.],
       [1., 3., 4.],
       [1., 4., 5.]])

In [42]:
spotify_training_data_matrix = linear_regression_data(spotify_training_data_input) 
spotify_objective= lambda weights: binary_logistic_regression_cost_function(spotify_training_data_matrix,\
                                                                    spotify_training_data_labels, weights)
spotify_gradient= lambda weights: binary_logistic_regression_gradient(spotify_training_data_matrix,\
                                                                    spotify_training_data_labels, weights)

spotify_initial_weights=np.zeros((len(spotify_training_data_matrix.T), 1))

s=len(spotify_training_data_matrix)

spotify_step_size=(3.9*s)/(np.linalg.norm(spotify_training_data_matrix))**2

spotify_optimal_weights,spotify_objective_values=gradient_descent_v2(spotify_objective, spotify_gradient, \
                                                        spotify_initial_weights,spotify_step_size, 1000, 100, 1e-2)

Iteration 100/1000, objective = 0.22372733676269302.
Iteration 200/1000, objective = 0.20311361947131654.
Iteration 300/1000, objective = 0.19292482679017547.
Iteration 400/1000, objective = 0.18637072867302748.
Iteration 500/1000, objective = 0.1817524285331569.
Iteration 600/1000, objective = 0.1783355175541878.
Iteration completed after 624/1000, objective = 0.17764570891883327.


In [43]:
Labels=binary_logistic_prediction_function(linear_model_function(spotify_training_data_matrix, spotify_optimal_weights))
spotify_classification_accuracy=classification_accuracy(Labels, spotify_training_data_labels)
print(spotify_classification_accuracy*100)

92.66666666666666


To increase the classification accuracy by considering the ridge binary logistic regression.

In [44]:
def ridge_binary_logistic_regression_cost_function(data_matrix, data_labels,
                                                   weights,
                                                   regularisation_parameter):
    L=binary_logistic_regression_cost_function(data_matrix, data_labels,weights)
    a=regularisation_parameter
    w=weights
    return L+(a/2)*np.linalg.norm(w)**2

In [45]:
def ridge_binary_logistic_regression_gradient(data_matrix, data_labels,
                                              weights,
                                              regularisation_parameter):
    dL=binary_logistic_regression_gradient(data_matrix, data_labels,weights)
    a=regularisation_parameter
    w=weights
    return dL+a*w

In [46]:
test_data_matrix = np.array([[1, -0.12793802, -0.19751682, 0.15226261], [1, -0.2000033, 0.52618148, 0.8782188],\
                             [1, -0.8613664, 0.30565866, -0.49296481], [1, -0.84047233, 0.9252299, 0.99071071],\
                             [1, -0.1042736, 0.52956168, -0.47798761], [1, 0.11284415, -0.94223132, 0.65812316],\
                             [1, -0.24878785, 0.85320211, -0.20377839], [1, 0.86694977, -0.55784702, 0.39560232],\
                             [1, 0.63581885, -0.11724269, -0.0979702], [1, 0.92166492, 0.76064856, 0.20755241]])
test_data_labels = np.array([[0], [1], [1], [1], [0], [1], [0], [0], [1], [0]])
test_weights = np.array([[-0.10541393], [0.57801403], [0.67163957],
                         [-0.34652194]])
regularisation_parameter = 1

ridge_binary_logistic_regression_cost_function(
        data_matrix=test_data_matrix,
        data_labels=test_data_labels,
        weights=test_weights,
        regularisation_parameter=regularisation_parameter)

1.3049910205825461

Write a function grid_search that performs a search for a minimum value of a given function on a given grid points. 

In [47]:
def grid_search(objective, grid):
    values = np.array([])
    for point in grid:
        values = np.append(values, objective(point))
    return grid[np.argmin(values)]

In [48]:
test_objective = lambda x: x[0]**2 - 2 * x[0] * x[1] + 2 * x[1]**2 + x[
    0] - 3 * x[1]
test_grid = [(x, y) for x in range(5) for y in range(5)]

grid_search(test_objective, test_grid)

(0, 1)

To find the optimal value of a hyperparameter regularisation_parameter and then find the spotify_optimal_weights corresponding to the value of the hyperparameter.

In [49]:
spotify_regularisation_parameter_grid = np.arange(0, .1, 0.01)

spotify_validation_error = lambda regularisation_parameter: 1-classification_accuracy(spotify_training_data_labels,\
                    binary_logistic_prediction_function(
                    binary_logistic_activation_function(
                    linear_model_function(spotify_training_data_matrix,
                    gradient_descent_v2(
                    objective = lambda weights: ridge_binary_logistic_regression_cost_function(
                                spotify_training_data_matrix,
                                spotify_training_data_labels,
                                weights,
                                regularisation_parameter),
                    gradient = lambda weights: ridge_binary_logistic_regression_gradient(
                                spotify_training_data_matrix,
                                spotify_training_data_labels,
                                weights,
                                regularisation_parameter),
                    initial_weights = np.zeros(shape = (spotify_training_data_matrix.shape[1], 1)),
                    step_size = 1/(np.linalg.norm(spotify_training_data_matrix)**2/(3.9*len(spotify_training_data_matrix))+regularisation_parameter),
                    no_of_iterations = 2000,
                    print_output = 2001,
                    tolerance = 1e-5
                    )[0]))))

spotify_optimal_regularisation_parameter = grid_search(
    spotify_validation_error, spotify_regularisation_parameter_grid)

spotify_optimal_weights = gradient_descent_v2(
    objective=lambda weights: ridge_binary_logistic_regression_cost_function(
        spotify_training_data_matrix, spotify_training_data_labels, weights,
        spotify_optimal_regularisation_parameter),
    gradient=lambda weights: ridge_binary_logistic_regression_gradient(
        spotify_training_data_matrix, spotify_training_data_labels, weights,
        spotify_optimal_regularisation_parameter),
    initial_weights=np.zeros(shape=(spotify_training_data_matrix.shape[1], 1)),
    step_size=1 /
    (np.linalg.norm(spotify_training_data_matrix)**2 /
     (3.9 * len(spotify_training_data_matrix)) + regularisation_parameter),
    no_of_iterations=2000,
    print_output=2001,
    tolerance=1e-5)[0]

spotify_training_regression_values = linear_model_function(
    spotify_training_data_matrix, spotify_optimal_weights)
spotify_training_predicted_labels = binary_logistic_prediction_function(
    binary_logistic_activation_function(spotify_training_regression_values))
spotify_classification_accuracy = classification_accuracy(true_labels=spotify_training_data_labels,\
                                                         recovered_labels=spotify_training_predicted_labels)
print(
    "The classification accuracy for the training set is {p:.2f} %. This is achieved for the hyperparameter value {a}"
    .format(p=100 * spotify_classification_accuracy,
            a=spotify_optimal_regularisation_parameter))

Iteration completed after 2000/2000, objective = 0.16459394936632762.
Iteration completed after 1637/2000, objective = 0.24916613118975584.
Iteration completed after 953/2000, objective = 0.2812102450711464.
Iteration completed after 677/2000, objective = 0.30325224596275335.
Iteration completed after 526/2000, objective = 0.3204602727013894.
Iteration completed after 431/2000, objective = 0.3347162465423249.
Iteration completed after 366/2000, objective = 0.34694808475640804.
Iteration completed after 318/2000, objective = 0.3576911694901299.
Iteration completed after 282/2000, objective = 0.36728610418910934.
Iteration completed after 253/2000, objective = 0.37596462132071534.
Iteration completed after 859/2000, objective = 0.3032522459685494.
The classification accuracy for the training set is 92.67 %. This is achieved for the hyperparameter value 0.03


## Music genre classification

To implement softmax function

In [51]:
def softmax_function(argument, axis=None):
    if axis == None:
        output = np.exp(argument - np.max(argument))
        output = output / np.sum(output)
    else:
        output = np.exp(argument - np.expand_dims(np.max(argument, axis), axis))
        output = output / np.expand_dims(np.sum(output, axis), axis)
    return output

In [52]:
softmax_function(np.array([[1.5], [0.3], [-3.7]]))

array([[0.76528029],
       [0.23049799],
       [0.00422172]])

To write a function multinomial_prediction_function that turns your predictions into labels. 

In [53]:
def multinomial_prediction_function(data_matrix, weight_matrix):
    Mod=linear_model_function(data_matrix, weight_matrix)
    return np.argmax(Mod, axis=1)

write a function one_hot_vector_encoding that converts an NumPy array labels with values in the range of {0,𝐾−1} into so-called one-hot vector encodings.

In [54]:
def one_hot_vector_encoding(labels):
    N = np.max(labels) + 1
    output = np.zeros((len(labels), N))
    output[np.arange(len(labels)), labels] = 1
    return output

In [55]:
one_hot_vector_encoding(np.array([1, 2, 0, 3]))

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

Implement the cost function and gradient for the multinomial logistic regression

In [56]:
def multinomial_logistic_regression_cost_function(data_matrix, weight_matrix,
                                                  one_hot_vector_encodings):
    s=len(data_matrix)
    mod = data_matrix @ weight_matrix
    return (np.sum(np.log(np.sum(np.exp(mod), axis=1)) \
                   - np.sum(one_hot_vector_encodings * mod, axis=1)))/s

In [57]:
def multinomial_logistic_regression_gradient(data_matrix, weight_matrix,
                                             one_hot_vector_encodings):
    mod = data_matrix @ weight_matrix
    s=len(data_matrix)
    return (data_matrix.T @(softmax_function(mod, axis=1) - one_hot_vector_encodings))/s

In [58]:
test_data_matrix = np.array([[6, 4, 5], [1, 2, 8], [-3, 3, 6], [6, 5, -100],
                             [5, 7, 2]])
test_weight_matrix = np.array([[2, 1, -2, -4], [2, -5, 1, 4], [-2, -3, -1,
                                                               -2]])
test_one_hot_vector_encoding = np.array([[1., 0., 0., 0.], [0., 0., 1., 0.],
                                         [0., 0., 0., 1.], [0., 1., 0., 0.],
                                         [1., 0., 0., 0.]])
multinomial_logistic_regression_cost_function(
        test_data_matrix, test_weight_matrix, test_one_hot_vector_encoding)

0.028611028678354876

In [59]:
GTZAN_data = np.genfromtxt('GTZAN_features.csv',
                           skip_header=True,
                           dtype=float,
                           delimiter=',',
                           usecols=range(1, 59))
GTZAN_data, _, _ = standardise(GTZAN_data)

genres_dictionary = {b'blues':0,b'classical':1,b'country':2,\
                    b'disco':3,b'hiphop':4,b'jazz':5,\
                     b'metal':6,b'pop':7,b'reggae':8,b'rock':9}
GTZAN_labels = np.genfromtxt('GTZAN_features.csv',
                             skip_header=True,
                             dtype=str,
                             delimiter=',',
                             usecols=[59],
                             converters={59: lambda x: genres_dictionary[x]})

In [60]:
GTZAN_data_matrix = linear_regression_data(GTZAN_data) 
GTZAN_OHV = one_hot_vector_encoding(GTZAN_labels)
GTZAN_objective= lambda weight_matrix: multinomial_logistic_regression_cost_function(GTZAN_data_matrix,\
                                                                        weight_matrix, GTZAN_OHV)
GTZAN_gradient = lambda weight_matrix:multinomial_logistic_regression_gradient(GTZAN_data_matrix,\
                                                                        weight_matrix, GTZAN_OHV)

s2=len(GTZAN_data_matrix)

GTZAN_step_size = (3.9*s2)/(np.linalg.norm(GTZAN_data_matrix))**2
GTZAN_initial_weights = np.zeros((GTZAN_data_matrix.shape[1], GTZAN_OHV.shape[1]))


GTZAN_optimal_weights, GTZAN_objective_values=gradient_descent_v2(GTZAN_objective, GTZAN_gradient,\
                      GTZAN_initial_weights, GTZAN_step_size, 1000, 100, 1e-3)

Iteration 100/1000, objective = 1.0767506389614978.
Iteration 200/1000, objective = 0.910981484867509.
Iteration 300/1000, objective = 0.8244841216515565.
Iteration 400/1000, objective = 0.7683732070923374.
Iteration 500/1000, objective = 0.7279186772726307.
Iteration 600/1000, objective = 0.6968211831203023.
Iteration 700/1000, objective = 0.6718623190153213.
Iteration 800/1000, objective = 0.6512000503453517.
Iteration 900/1000, objective = 0.6336912713100291.
Iteration 1000/1000, objective = 0.6185821006106668.
Iteration completed after 1000/1000, objective = 0.6185821006106668.


In [61]:
np.linalg.norm(GTZAN_optimal_weights)

6.581158794776619

In [62]:
GTZAN_objective_values[-1]

0.6184412193103138

In [63]:
GTZAN_recovered_labels = multinomial_prediction_function(GTZAN_data_matrix, \
                                                         GTZAN_optimal_weights)
GTZAN_classification_accuracy = classification_accuracy(
    GTZAN_labels, GTZAN_recovered_labels)
print("The classification accuracy for the GTZAN dataset is {p} %.".format(
    p=100 * GTZAN_classification_accuracy))

The classification accuracy for the GTZAN dataset is 81.89999999999999 %.


In [64]:
def soft_thresholding(argument, threshold):
    return np.sign(argument) * np.maximum(0, np.abs(argument) - threshold)

In [65]:
def lasso_logistic_regression_cost_function(data_matrix, weight_matrix,
                                            one_hot_vector_encodings,
                                            regularisation_parameter):
    MSE=multinomial_logistic_regression_cost_function(data_matrix, weight_matrix,one_hot_vector_encodings)
    a=regularisation_parameter
    return MSE+a * np.sum(np.abs(weight_matrix))

In [66]:
def proximal_gradient_descent(objective,
                              gradient,
                              proximal_map,
                              initial_weights,
                              step_size=1,
                              no_of_iterations=1000,
                              print_output=100):
    obj_list=[]
    W=initial_weights
    print(gradient)
    obj_list.append(objective(W))
    N=no_of_iterations
    s=step_size
    for i in range(N):
        W=proximal_map(W-s*gradient(W))
        obj_list.append(objective(W))
        if (i+1)%print_output==0:
            print("Iteration {k}/{m}, objective={o}.".format(k=i+1,m=no_of_iterations, o=obj_list[i]))
    print("Iteration completed after {k}/{m}, objective = {o}.".format(k=i+1,m=no_of_iterations, o=obj_list[i]))
    return W,obj_list

In [67]:
test_weight_matrix = np.array([[1, 2], [3, -4]])
soft_thresholding(test_weight_matrix, 2)

array([[ 0,  0],
       [ 1, -2]])

In [68]:
LASSO_regularisation_parameter = 1e-4

GTZAN_LASSO_objective= lambda weight_matrix: lasso_logistic_regression_cost_function(GTZAN_data_matrix,\
                                           weight_matrix, GTZAN_OHV,LASSO_regularisation_parameter)
GTZAN_LASSO_gradient = lambda weight_matrix:multinomial_logistic_regression_gradient(GTZAN_data_matrix,\
                                                                        weight_matrix, GTZAN_OHV)

k=LASSO_regularisation_parameter*GTZAN_step_size
GTZAN_proximal_map = lambda arg:soft_thresholding(arg, k)


GTZAN_LASSO_optimal_weights, GTZAN_LASSO_objective_values=proximal_gradient_descent(GTZAN_LASSO_objective,GTZAN_LASSO_gradient,\
                              GTZAN_proximal_map, GTZAN_initial_weights, GTZAN_step_size, 1000,100)

<function <lambda> at 0x7fa1508fee50>
Iteration 100/1000, objective=1.0825816929822865.
Iteration 200/1000, objective=0.9188065638028389.
Iteration 300/1000, objective=0.8337438517624016.
Iteration 400/1000, objective=0.7787614112668051.
Iteration 500/1000, objective=0.7392524994112956.
Iteration 600/1000, objective=0.7089861854744975.
Iteration 700/1000, objective=0.6847639172736621.
Iteration 800/1000, objective=0.6647871984883266.
Iteration 900/1000, objective=0.6479213697436089.
Iteration 1000/1000, objective=0.6334014439684763.
Iteration completed after 1000/1000, objective = 0.6334014439684763.


In [69]:
GTZAN_recovered_labels = multinomial_prediction_function(GTZAN_data_matrix,GTZAN_LASSO_optimal_weights)
GTZAN_LASSO_classification_accuracy = classification_accuracy(GTZAN_labels, GTZAN_recovered_labels)
print("The classification accuracy for the GTZAN dataset is {p} %.".format(p=100 * GTZAN_classification_accuracy))

The classification accuracy for the GTZAN dataset is 81.89999999999999 %.
